### ISSUE TITLE
Take sparse matrix as input

### ISSUE THREAD

**Issue by zrq0123** [rdong08/GiniClust3#4]
Hi,  there are some problems (the error is "sparse matrix length is ambiguous“) when I use sparse matrix (from scipy.sparse ) as the input, because you use len function to get the row  num of the matrix when calculate gini or fano. I think sparse matrix is more memory-efficient and necessary for large datasets.  It is better to modify the code to support it

**Comment by rdong08** [comment]
Thanks a lot for your great suggestion. The current version of GiniCluster3 is not supporting sparse matrix, and I will made an update to support sparse matrix in the next version of GiniCluster3.
